  
 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace WebDocs.Common.Enum.DbLookupTables
{

        public enum EnumFileCategories : int
	    {
        }
        public enum EnumFileShareStatues : int
	    {
Public = 1,Private = 2,Hidden = 6        }
        public enum EnumFileViewStatuses : int
	    {
Locked = 1,Available = 2        }
        public enum EnumNotificationTypes : int
	    {
Share_Request = 1,Request_File_Upload = 2,Download = 3,Revoked = 4,Unshare = 5        }
}




